export const ERROR_CODES = {
    // General
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    NOT_FOUND: "NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",

    // Authentication
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",

    // User
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

    // Project
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    PROJECT_ALREADY_EXISTS: "PROJECT_ALREADY_EXISTS",
    PROJECT_ALREADY_ALLOCATED: "PROJECT_ALREADY_ALLOCATED",
    PROJECT_NOT_AVAILABLE: "PROJECT_NOT_AVAILABLE",

    // Teacher
    TEACHER_NOT_FOUND: "TEACHER_NOT_FOUND",
    MENTOR_LIMIT_REACHED: "MENTOR_LIMIT_REACHED",

    // Student
    STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",

    // Allocation
    ALLOCATION_FAILED: "ALLOCATION_FAILED",
    ALREADY_ALLOCATED: "ALREADY_ALLOCATED",

    // Database
    DATABASE_ERROR: "DATABASE_ERROR",
    DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",

    // Redis
    REDIS_ERROR: "REDIS_ERROR",
    REDIS_UNAVAILABLE: "REDIS_UNAVAILABLE",

    // External services
    FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
    EMAIL_FAILED: "EMAIL_FAILED"
} as const;